CREATE DATABASE WEBTEST_v1
DROP DATABASE WEBTEST_v1


CREATE TABLE QUYEN
(
MAQ CHAR(6) NOT NULL,
TENQUYEN NVARCHAR(30),
CONSTRAINT MQ_PK PRIMARY KEY (MAQ)
);

CREATE TABLE TAIKHOAN
(
MATK CHAR(6) NOT NULL,
MATKHAU VARCHAR(20),
MAQ CHAR(6),
NG_TAO_TK SMALLDATETIME,
AVATA VARCHAR(100),
CONSTRAINT MTK_PK PRIMARY KEY (MATK),
CONSTRAINT TK_Q_FK FOREIGN KEY (MAQ) REFERENCES QUYEN(MAQ)
);

CREATE TABLE HOCVIEN
(
	MAHV CHAR(6) NOT NULL,
	TENHV NVARCHAR(50) NOT NULL,
	NGSINH SMALLDATETIME,
	GIOITINH NCHAR(5),
	EMAIL VARCHAR(50),
	DCHI NVARCHAR(150),
	SDT CHAR(12),
	CONSTRAINT MHV_PK PRIMARY KEY (MAHV),
	CONSTRAINT HV_TK_FK FOREIGN KEY (MAHV) REFERENCES TAIKHOAN(MATK)
);

CREATE TABLE GIAOVIEN
(
	MAGV CHAR(6) NOT NULL,
	TENGV NVARCHAR(50) NOT NULL,
	NGSINH SMALLDATETIME,
	GIOITINH NCHAR(5),
	EMAIL VARCHAR(50),
	DCHI NVARCHAR(150),
	SDT CHAR(12),
	NGVL SMALLDATETIME,
	CHUNGCHI NVARCHAR(300),
	CONSTRAINT MGV_PK PRIMARY KEY (MAGV),
	CONSTRAINT GV_TK_FK FOREIGN KEY (MAGV) REFERENCES TAIKHOAN(MATK)
);

CREATE TABLE KHOAHOC
(
MAKH CHAR(6) NOT NULL,
TENKH NVARCHAR(50),
HOCPHI INT,
MOTA NVARCHAR(300),
CONSTRAINT MKH_PK PRIMARY KEY (MAKH)
);

CREATE TABLE LOP
(
MALOP CHAR(6) NOT NULL,
TENLOP NVARCHAR(50),
MAGV CHAR(6),
MAKH CHAR(6),
THONGTINKHAC NVARCHAR(400),
CONSTRAINT ML_PK PRIMARY KEY (MALOP),
CONSTRAINT L_GV_FK FOREIGN KEY (MAGV) REFERENCES GIAOVIEN(MAGV),
CONSTRAINT L_KH_FK FOREIGN KEY (MAKH) REFERENCES KHOAHOC(MAKH)
);

CREATE TABLE HOC
(
MAHV CHAR(6) NOT NULL,
MALOP CHAR(6) NOT NULL,
TGBD SMALLDATETIME,
TGKT SMALLDATETIME,
KQ FLOAT,
XEPLOAI VARCHAR(30),
CONSTRAINT MHV_ML_PK PRIMARY KEY (MAHV,MALOP),
CONSTRAINT H_HV_FK FOREIGN KEY (MAHV) REFERENCES HOCVIEN(MAHV),
CONSTRAINT H_L_FK FOREIGN KEY (MALOP) REFERENCES LOP(MALOP)
);

CREATE TABLE BAITEST
(
MABT CHAR(6) NOT NULL,
TENBT NVARCHAR(50),
MALOP CHAR(20),
TGLAMBAI SMALLDATETIME,
GHICHU NVARCHAR(200),
username CHAR(20), //Co can thiet hay khong?

CONSTRAINT MBT_PK PRIMARY KEY (MABT),
CONSTRAINT BT_KH_FK FOREIGN KEY (MAKH) REFERENCES KHOAHOC(MAKH),
CONSTRAINT BT_TK_FK FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK)
);

CREATE TABLE CAUHOI
(
MACH CHAR(6) NOT NULL,
MABT CHAR(6),
ND NVARCHAR(500),
CONSTRAINT MCH_PK PRIMARY KEY (MACH),
CONSTRAINT CH_BT_FK FOREIGN KEY (MABT) REFERENCES BAITEST(MABT)
);

CREATE TABLE LUACHON
(
MALC CHAR(6) NOT NULL,
MACH CHAR(6),
ND NVARCHAR(500),
LADUNG INT, -- 1 DUNG, 0 SAI
CONSTRAINT MLC_PK PRIMARY KEY (MALC),
CONSTRAINT LC_CH_FK FOREIGN KEY (MACH) REFERENCES CAUHOI(MACH)
);

CREATE TABLE KETQUA
(
MATK CHAR(6) NOT NULL,
MABT CHAR(6) NOT NULL,
LAN INT NOT NULL,
TGBD SMALLDATETIME,
TGKT SMALLDATETIME,
DIEM FLOAT,
CONSTRAINT MTK_MBT_LAN_PK PRIMARY KEY (MATK,MABT,LAN),
CONSTRAINT KQ_TK_FK FOREIGN KEY (MATK) REFERENCES TAIKHOAN(MATK),
CONSTRAINT KQ_BT_FK FOREIGN KEY (MABT) REFERENCES BAITEST(MABT)
);

/*CREATE TABLE CHUDE
(
MACD CHAR(6) NOT NULL,
TENCD NVARCHAR(50),
MOTA NVARCHAR(300),
CONSTRAINT MCD_PK PRIMARY KEY (MACD)
);
CREATE TABLE BAIHOC
(
MABH CHAR(6) NOT NULL,
MACD CHAR(6),
TENBH NVARCHAR(50),
MANGUOIDANG CHAR(6),
MOTA NVARCHAR(300),
ND NVARCHAR(500),
GIA INT,
CONSTRAINT MBH_PK PRIMARY KEY (MABH),
CONSTRAINT BH_CD_FK FOREIGN KEY (MACD) REFERENCES CHUDE(MACD),
CONSTRAINT BH_GV_FK FOREIGN KEY (MANGUOIDANG) REFERENCES GIAOVIEN(MAGV)
);*/


